### ISSUE TITLE
글, 댓글 감정 표현 안됨

### ISSUE THREAD

**Issue by Pyohwan** [JakduK/jakduk-web#100]
API 날릴때 path에 LIKE -> like 로 dislike -> dislike 로 해야 할듯
현재 400에 "파라미터 값이 틀리거나 존재하지 않습니다." 로 API 에서 응답하는데, 웹에서는 "내가 쓴 글에 좋아요 싫어요를 할수 없어요." 라고 메시지를 보내는데요. 그냥 API에서 보내준 메시지를 웹에서도 보여주는게 편하지 않나요? 어찌 생각함?

**Comment by silverprize** [comment]
@Pyohwan api마다 lang 쿼리를 붙여야 하는 번거로움이 있기 때문이죠.

**Comment by Pyohwan** [comment]
@silverprize 
어라.. lang으로 한번 지정하면 다음 API 날릴때에는 lang 없이도 지정한 lang으로 지정되어야 하는데요.
그리 안되는 거면 의도한 바가 아닙니다.

**Comment by silverprize** [comment]
@Pyohwan lang쿠기가 있으니까 지정된 것 처럼 보이는 것이지 db에 저장하는 건 아니잖아요.

**Comment by Pyohwan** [comment]
@silverprize 쿠키에 저장하는것 정도(즉, 내 브라우저)면 되는거 아닌가요? DB로 관리할 정도인가요?
필요한게 무엇인지..?

**Comment by silverprize** [comment]
완료
