### ISSUE TITLE
사진 지우기 API 호출 안됨

### ISSUE THREAD

**Issue by Pyohwan** [JakduK/jakduk-web#101]
사진 업로드 하고나서 X 눌러서 지우는데.. 이때 지우기 API 호출을 해줘야 함.

근데 이거는 asciidoc 나오면 작업하시죠. 천천히..

**Comment by silverprize** [comment]
새글 작성중이면 임시 상태니까 알아서 없어질테고 수정중이라면 글저장 완료되면 호출합니다.

**Comment by Pyohwan** [comment]
@silverprize 임시 상태를 배치로 지워주진 않아요. 임시 파일 지워주는 배치잡은 있긴 한데 주기적으로 돌지 않음.

**Comment by silverprize** [comment]
배치 믿고 그대로 두겠습니다.

**Comment by silverprize** [comment]
서버관리를 클라이언트에게 의존하지 맙시다.
