### ISSUE TITLE
쿠키 이슈와 관련하여 api, dev 도메인은 통합해야 할듯

### ISSUE THREAD

**Issue by Pyohwan** [JakduK/jakduk-web#110]
<img width="1308" alt="2017-10-25 6 04 01" src="https://user-images.githubusercontent.com/1825642/31990075-0256280a-b9af-11e7-8e91-6ded322b7061.png">

org.springframework.web.servlet.i18n.CookieLocaleResolver.LOCALE api와 web이 같이 활용하기 위해서는 도메인을 통합시키는게 최선일듯

- dev-web.jakduk.com -> dev.jakduk.com/web
- dev-api.jakduk.com -> dev.jakduk.com/api
- 기존 local 쿠키는 삭제
- HTTP 요청 마다 lang 파라미터 넣어주는것도 삭제
  - 카테고리 목록 API, 통계 API 등

**Comment by silverprize** [comment]
아뇨 api서버에서 쿠키 도메인 `jakduk.com` -> `.jakduk.com` 으로 바꿔주세요.

**Comment by silverprize** [comment]
아 그러면 prd랑 공유되는구나.

**Comment by silverprize** [comment]
api서버 쿠키이름을 lang으로 바꾸는게 최선 일듯.

**Comment by Pyohwan** [comment]
쿠키 이름을 lang으로 하든 org.springframework.web.servlet.i18n.CookieLocaleResolver.LOCALE 로 하든 jakduk-api, jakduk-web의 도메인이 다른 이상 공유가 안되고요.

도메인을 합치는게 이상하면 지금처럼 lang 파라미터로 둬도 상관 없을듯..
