### ISSUE TITLE
안됨

### ISSUE THREAD

**Issue by Pyohwan** [JakduK/jakduk-web#111]
리얼 환경 -> 자유 게시판 -> 공지글의 클래시카 풋살단의 메인 스폰서가 되었습니다. 클릭 -> ???

**Comment by silverprize** [comment]
잘됨.

**Comment by Pyohwan** [comment]
![2017-11-02 11 27 44](https://user-images.githubusercontent.com/1825642/32331144-8037c7ac-c025-11e7-890a-e578c9777eed.png)

**Comment by Pyohwan** [comment]
![2017-11-02 11 28 49](https://user-images.githubusercontent.com/1825642/32331185-9c39c342-c025-11e7-932b-d6f914464555.png)

**Comment by silverprize** [comment]
첫번째 774 헤더도 보여주세요.

**Comment by Pyohwan** [comment]
![2017-11-03 12 21 06](https://user-images.githubusercontent.com/1825642/32334096-ed41c35a-c02c-11e7-8be3-6058310daf2e.png)

원한다면 다 해줘야죠.

**Comment by Pyohwan** [comment]
@silverprize 재시작 해도 안됩니다.
이 문제의 원인은 자유게시판에서 축구게시판에 있는 글을 볼려고 하니 그런거고요.
그래서 301로 
```
location:https://api.jakduk.com/api/board/football/774
```
이 뜨는거고요.
애초에 글을 클릭하면 위 URL로 접속하면 되면 해결되는 겁니다.

만약 URL을 jakduk-web에서 생성하는게 번거롭다면
jakduk-api에서 URL을 생성해서 내려줄 용의는 있습니다. 썸네일도 URL 주는것처럼요.

원하는데로 해줌.

**Comment by silverprize** [comment]
nginx나 브라우저 캐시 때문인 것 같습니다만...

**Comment by Pyohwan** [comment]
10일 전부터 안되던 건데 아직도 캐시가 남아 있을까요? 
일단 제폰에서도 안되는것을 보아 브라우저캐시는 아닌듯

**Comment by Pyohwan** [comment]
여전히 안되는데요.

**Comment by silverprize** [comment]
브라우저 캐시요.
https://stackoverflow.com/questions/9130422/how-long-do-browsers-cache-http-301s?answertab=votes#tab-top

**Comment by Pyohwan** [comment]
```
Cache-Control: no-store, no-cache, must-revalidate
Expires: Thu, 01 Jan 1970 00:00:00 GMT
```
추가할 테니 기다리세요.

**Comment by silverprize** [comment]
😢제 잘못이었습니다.
