### ISSUE TITLE
인기 검색어 누르면 콘솔 에러

### ISSUE THREAD

**Issue by Pyohwan** [JakduK/jakduk-web#120]
* 홈에서 왼쪽 인기 검색어 중 `정전` 누름
* 검색 화면에서 상단 `정전` 누름

![2018-04-03 12 07 17](https://user-images.githubusercontent.com/1825642/38201354-fcadbb9c-36d2-11e8-96a4-a539e9b5eacc.png)
콘솔 에러

**Comment by Pyohwan** [comment]
@silverprize 
엘라스틱서치도 마이그레이션이 필요했네요. 적용했습니다.

**Comment by silverprize** [comment]
@Pyohwan 담당자가 처리하시죠
