### ISSUE TITLE
글 쓰자 마자 조회수 2회?

### ISSUE THREAD

**Issue by Pyohwan** [JakduK/jakduk-web#129]
글을 쓰자 마자 누가 내 글을 봤을까요? 0회가 되어야 하지 않을까요?

**Comment by silverprize** [comment]
내가 1빠니까 1회

**Comment by silverprize** [comment]
@Pyohwan 쿠키가 FREE_BOARD -> ARTICLE로 바꼈네요
쿠키이름 바꾸고 안알려주기 있기 없기?

**Comment by Pyohwan** [comment]
오잉 제 잘못인가요 ㅜㅜ

**Comment by silverprize** [comment]
@Pyohwan 글작성api response에 어뷰징쿠키 넣어줘야 됩니다.

**Comment by Pyohwan** [comment]
@silverprize 해결 된건가요?

**Comment by silverprize** [comment]
@Pyohwan api 수정해주세요.

**Comment by Pyohwan** [comment]
@silverprize 뭘요?

**Comment by silverprize** [comment]
@Pyohwan 글작성api response에 어뷰징쿠키 넣어줘야 됩니다.

**Comment by Pyohwan** [comment]
`ARTICLE_{seq}` 쿠키 말하나요?
글작성 api에 넣어달라는 말은 조회수 0을 만들기 위함인가요?
설명좀 길게 해주세요 ㅜㅜ

**Comment by silverprize** [comment]
맞습니다.
필요한 설명을 직접 하셨네요.

**Comment by Pyohwan** [comment]
그럼 의견을 받아들이는 걸로 하고 1회로 하시죠 ㅋㅋ

**Comment by silverprize** [comment]
👌
