### ISSUE TITLE
연도별 관중수에 2018년 추가 필요

### ISSUE THREAD

**Issue by Pyohwan** [JakduK/jakduk-web#133]
https://jakduk.com/stats/attendance?category=season

그리고 년도 콤보박스 누름시 2018년이 가장 위에 있도록요. 내림차순

**Comment by silverprize** [comment]
내림차순은 api에서 하세요

**Comment by Pyohwan** [comment]
@silverprize 
연도 목록은 API 에서 주는거 맞나요?? 아니면 주길 바란다는 뜻인지??

**Comment by silverprize** [comment]
요구사항을 오해했습니다.
차트 데이터 정렬 말한줄
