### ISSUE TITLE
텔레그램 초대 링크 만료된듯

### ISSUE THREAD

**Issue by Pyohwan** [JakduK/jakduk-web#145]
![스크린샷 2019-10-10 오전 12 09 24](https://user-images.githubusercontent.com/1825642/66494207-401ae380-eaf2-11e9-8704-8e18f2aafc8a.png)

저기서 텔레그램 누르고, 텔레그램 데스크탑으로 열지 물어보는데, 수락 하면 링크 만료됐거나 올바르지 않다네요.

**Comment by silverprize** [comment]
비공개방으로 바꿨기 때문이죠.
