### ISSUE TITLE
One of your dependencies has a security vulnerability

### ISSUE THREAD

**Issue by Pyohwan** [JakduK/jakduk-web#146]
이런게 메일로 수도 없이 날라옵니다.
취약점이 없는 작두를 만둘어주세요.

![스크린샷 2019-10-10 오전 9 49 24](https://user-images.githubusercontent.com/1825642/66530576-49806c00-eb43-11e9-93f2-b7d23fa35d5f.png)

**Comment by silverprize** [comment]
감당하셔야합니다.
