### ISSUE TITLE
sitemap.xml 에 접근이 안되요

### ISSUE THREAD

**Issue by Pyohwan** [JakduK/jakduk-web#147]
무엇이 문제일까요?

**Comment by silverprize** [comment]
감당하셔야합니다.

**Comment by Pyohwan** [comment]
@silverprize 
어허...
https://api.jakduk.com/rss

근데 /sitemap.xml 과 통일 하는게 좋을것 같네요. rss.xml 로 할께요.

**Comment by silverprize** [comment]
@Pyohwan nginx rewrite 설정하시면 됩니다.

**Comment by Pyohwan** [comment]
@silverprize 
네 nginx 로 처리할께요. jakduk-web 에 있는 sitemap, rss 프록시 코드는 지워주세요.
