### ISSUE TITLE
글쓰기 제목 검증 3자 이상인데

### ISSUE THREAD

**Issue by Pyohwan** [JakduK/jakduk-web#25]
1자 이상으로 완화 시키는것에 대해 어떻게 생각하시나요?

**Comment by silverprize** [comment]
@Pyohwan 제목을 없애버립시다.

**Comment by Pyohwan** [comment]
본문만 있는건가요?

**Comment by silverprize** [comment]
네 트위터 처럼요

**Comment by Pyohwan** [comment]
구체적으로 설명좀.. 글 목록과 상세는 어찌 보이나요? 댓글은?

**Comment by silverprize** [comment]
자유롭게 한글자도 유효한 것으로 해요
최소 글자수 제한은 매우 한국스러워요

**Comment by Pyohwan** [comment]
한글자 제한 할거면 그냥 제목 안쓰고 본문만 써도 되는걸로 하는게 더 낫지 않음?

**Comment by silverprize** [comment]
정확히 말하면 제목은 필수이나 글자수 제한은 두지 않는다는 거시죠

**Comment by Pyohwan** [comment]
필수는 null이 될수 없는데, 글자수 제한을 안두면 null 이 될수도 있다는 소리니 둘다 성립이 불가능합니다.

**Comment by silverprize** [comment]
대화가 점점 늪으로...
