### ISSUE TITLE
찾기 결과에서 글 목록을 누르면 링크 가기 안됨

### ISSUE THREAD

**Issue by Pyohwan** [JakduK/jakduk-web#26]
대상 : 스테이징

https://staging.jakduk.com/search?q=123&w=PO;CO;GA;

위 링크로 들어가보면 검색 결과가 나오는데, 검색 결과의 게시물을 클릭하면 링크 안감.

**Comment by silverprize** [comment]
@Pyohwan 완전 잘되는데요?

**Comment by Pyohwan** [comment]
@silverprize 

https://staging.jakduk.com/search?q=test&w=PO;CO;GA

여기서 해보세요.
