### ISSUE TITLE
Summernote 업데이트

### ISSUE THREAD

**Issue by Pyohwan** [JakduK/jakduk-web#28]
지금 버전이 낮은것 같아요.
Summernote 버전 좀 올려주세요. 이왕이면 anguler-summernote 말고 오리지날 summernote로 하면 더 좋음.

**Comment by silverprize** [comment]
https://github.com/summernote/summernote/releases
최신 버전이랑 0.0.1 차이 밖에 안납니다

**Comment by Pyohwan** [comment]
angular-summernote 없애주세요.
