### ISSUE TITLE
localhost:3000 GA 수집 제외 필요

### ISSUE THREAD

**Issue by Pyohwan** [JakduK/jakduk-web#37]
<img width="646" alt="2016-10-07 9 29 33" src="https://cloud.githubusercontent.com/assets/1825642/19175346/b79ffd20-8c70-11e6-88bd-c735efdfe5f9.png">

로컬에서 jakduk-web을 띄웠을때 /home에서 GA가 동작 하는듯

**Comment by silverprize** [comment]
`config/environment/local.js` 아래 내용으로 만들어 주세요.
```
{
  gaAccount: ''
}
```
