### ISSUE TITLE
구글 웹마스터 파일 접근 안됨

### ISSUE THREAD

**Issue by Pyohwan** [JakduK/jakduk-web#44]
<img width="735" alt="2016-12-02 2 03 00" src="https://cloud.githubusercontent.com/assets/1825642/20803751/9fe1bb76-b833-11e6-9b5d-6c4afee1caf2.png">

접근 가능하게 해주세요. 
네이버 웹마스터 파일도 있으니 함께 접근가능하게 해줘용

naverd292dd6a4dddaa4d061833bc02807467.html

**Comment by silverprize** [comment]
@Pyohwan 파일 주세용

**Comment by Pyohwan** [comment]
https://github.com/JakduK/jakduk-api/blob/develop/api/src/main/webapp/google29dc471fb0dd6e4c.html
https://github.com/JakduK/jakduk-api/blob/develop/api/src/main/webapp/naverd292dd6a4dddaa4d061833bc02807467.html
