### ISSUE TITLE
PRD 사진 올리기 안됨.

### ISSUE THREAD

**Issue by Pyohwan** [JakduK/jakduk-web#59]
![image](https://cloud.githubusercontent.com/assets/1825642/21931829/e1da3dea-d9e0-11e6-87b4-e44492b2e99e.png)

File.lastModifiedDate는 더이상 사용되지 않습니다. 대신 File.lastModified를 사용하세요.  angular-file-upload.min.js:6:10415

**Comment by silverprize** [comment]
@Pyohwan api서버 504에러
![2017-01-14 10 33 49](https://cloud.githubusercontent.com/assets/860087/21951087/f6d8d40e-da44-11e6-9c1c-d63e32c57515.png)

**Comment by silverprize** [comment]
완전 잘됨.
