### ISSUE TITLE
회원 프로필 사진 추가

### ISSUE THREAD

**Issue by Pyohwan** [JakduK/jakduk-web#64]
기다리고 기다리던 회원 프로필 사진을 추가했습니다. 회원 프로필 사진을 추가 했을때의 회원 가입 플로우를 정리해봤습니다.

### 추가된 API
프로필 사진 올리기 https://staging.jakduk.com:8080/swagger-ui.html#!/User/uploadUserPictureUsingPOST

### 수정된 API
이메일 기반 회원 가입 https://staging.jakduk.com:8080/swagger-ui.html#!/User/addJakdukUserUsingPOST
SNS기반 회원 가입 https://staging.jakduk.com:8080/swagger-ui.html#!/User/addSocialUserUsingPOST
SNS 기반 회원 가입시 필요한 회원 프로필 정보 https://staging.jakduk.com:8080/swagger-ui.html#!/Authentication/getSocialAttemptedUserUsingGET
/api/auth/user https://staging.jakduk.com:8080/swagger-ui.html#!/Authentication/getMyProfileUsingGET

# 이메일 기반 회원 가입 하기
## 가입 하기
https://staging.jakduk.com:8080/swagger-ui.html#!/User/addJakdukUserUsingPOST
이 API를 보면 userPictureId 필드가 추가 되었는데, 이 필드의 값은
https://staging.jakduk.com:8080/swagger-ui.html#!/User/uploadUserPictureUsingPOST
에서 얻은 ID를 넣어주면 됨.

# 확인 하기
로그인을 하고 https://staging.jakduk.com:8080/swagger-ui.html#!/Authentication/getMyProfileUsingGET 를 날려보면 picture 필드에 사진 정보가 들어가 있으면 성공함.

# SNS 계정으로 회원 가입 하기
## SNS 로그인 시도
https://staging.jakduk.com:8080/swagger-ui.html#!/Authentication/loginSocialUserUsingPOST 를 날려서 로그인을 시도하면, 만일 가입되지 않았다면 가입을 하라고 함. http response header에 x-attempt-token 정보를 줄것임

## SNS 회원 추가 정보 입력
회원 가입 입력 폼이 뜨고(이메일, 닉네임, 소개, 지지구단, 프로필 사진 등..), 이들의 값들은 https://staging.jakduk.com:8080/swagger-ui.html#!/Authentication/getSocialAttemptedUserUsingGET 에서 받은것으로 채워준다. 기본적으로 SNS로 가입할때에는 SNS에 있는 프로필 사진을 처음에 보여준다. 사용자가 SNS 프로필 사진을 사용을 원치 않을때에는 직접 사진을 올릴수도 있다. 

## SNS 회원 추가 API 호출 할때
SNS 프로필 사진을 작두왕에서 그대로 사용코자 할때에는, http://localhost:8080/swagger-ui.html#!/User/addSocialUserUsingPOST 에서 externalLargePictureUrl에 값을 넣어주면 된다. (externalLargePictureUrl은 https://staging.jakduk.com:8080/swagger-ui.html#!/Authentication/getSocialAttemptedUserUsingGET 에서 얻을 수 있다)

SNS 프로필 사진을 쓰기 싫고 직접 올릴때에는  https://staging.jakduk.com:8080/swagger-ui.html#!/User/uploadUserPictureUsingPOST 를 통해 이미지를 업로드 하고 응답 데이터의 ID를 userPictureId에 넣어주면 된다.

SNS 계정 회원 가입에서 프로필 사진 확인 하는 방법은 위 이메일 기반의 확인 하기 참고.

**Comment by Pyohwan** [comment]
내 프로필 정보 보기 https://staging.jakduk.com:8080/swagger-ui.html#!/User/getProfileMeUsingGET
내 프로필 정보 편집 https://staging.jakduk.com:8080/swagger-ui.html#!/User/editProfileMeUsingPUT

에도 회원 사진 적용되었음

**Comment by silverprize** [comment]
@Pyohwan writer에 다 넣어주세요.

**Comment by Pyohwan** [comment]
@silverprize 다 들어갑니다. 다만 기존꺼는 안들어가 있음. 사진 넣은사람만 앞으로 나와요.

**Comment by silverprize** [comment]
@Pyohwan 스테이지 서버 계정에 일괄 기본 이미지 넣어주세요.

**Comment by Pyohwan** [comment]
@silverprize 뭐 좋은거 없나요? 추천좀

**Comment by silverprize** [comment]
@Pyohwan 작두킹로고

**Comment by Pyohwan** [comment]
https://staging.jakduk.com:8080/images/logo_16.png
https://staging.jakduk.com:8080/images/logo_32.png
https://staging.jakduk.com:8080/images/logo_48.png
https://staging.jakduk.com:8080/images/logo_128.png
https://staging.jakduk.com:8080/images/logo_256.png
https://staging.jakduk.com:8080/images/logo_1024.png
https://staging.jakduk.com:8080/images/logo_type_A_en.png
https://staging.jakduk.com:8080/images/logo_type_A_kr.png
https://staging.jakduk.com:8080/images/logo_type_B_en.png
https://staging.jakduk.com:8080/images/logo_type_B_kr.png

골라 잡으세요

**Comment by silverprize** [comment]
@Pyohwan logo_256.png

**Comment by silverprize** [comment]
아바타 등록/변경은 추후 마일스톤에서.
