### ISSUE TITLE
게시물 썸네일 URL 추가

### ISSUE THREAD

**Issue by Pyohwan** [JakduK/jakduk-web#66]
홈에서 보여줄 각종 최근 데이터 가져오기 https://staging.jakduk.com:8080/swagger-ui.html#!/Home/getLatestUsingGET
자유게시판 글 목록 https://staging.jakduk.com:8080/swagger-ui.html#!/BoardFree/getFreePostsUsingGET

위 두개의 API에 thumbnailUrl 필드가 추가되었습니다.

**Comment by silverprize** [comment]
적용
