### ISSUE TITLE
좋아요/싫어요 취소 추가

### ISSUE THREAD

**Issue by Pyohwan** [JakduK/jakduk-web#67]
글과 댓글에 대하여 로그인 회원이 좋아요/싫어요 취소가 가능해졌음. 좋아요 API를 한번더 요청하면 취소가 됩니다.
만일 현재 좋아요 상태인데, 싫어요를 선택하면 좋아요가 취소되고 싫어요로 바뀜.

### 수정된 API 목록
댓글 감정 표현
https://staging.jakduk.com:8080/swagger-ui.html#!/BoardFree/addFreeCommentFeelingUsingPOST
글 감정 표현
https://staging.jakduk.com:8080/swagger-ui.html#!/BoardFree/addFreeFeelingUsingPOST
글 상세
https://staging.jakduk.com:8080/swagger-ui.html#!/BoardFree/getFreePostUsingGET
글의 댓글 목록
https://staging.jakduk.com:8080/swagger-ui.html#!/BoardFree/getFreePostCommentsUsingGET

위 API에 공통적으로 myFeeling 필드가 들어갔는데 이는 로그인 회원의 현재 감정 상태가 무엇인지를 나타낸다.

**Comment by silverprize** [comment]
@Pyohwan myFeeling이 따로 있을게 아니고 기존것에 로그인한 사람의 것을 반영 시켜주세요.

**Comment by Pyohwan** [comment]
@silverprize myFeeling이 로그인한 사람의 감정이에요.

**Comment by Pyohwan** [comment]
위 API에 공통적으로 myFeeling 필드가 들어갔는데 이는 로그인 회원의 현재 감정 상태가 무엇인지를 나타낸다.

위 본문 마지막 문장 참조

**Comment by silverprize** [comment]
@Pyohwan 그말이 아니고 usersDisliking, usersLiking과 myFeeling이 중복이니 usersDisliking, usersLiking에 로그인한 사람것이 있으면 반영을 해달라구요.

**Comment by silverprize** [comment]
@Pyohwan 오해했네요 usersDisliking, usersLiking에 다 들어 있으니 myFeeling이 필요없겠네요.

**Comment by Pyohwan** [comment]
@silverprize 맞아요. 다 들어가있어요. 배열에서 userID로 있는지 검사하면 되긴 한데, 작업하기 힘들까봐 빼놨어요.
usersDisliking과 usersLiking의 존재 이유는 누가누가 눌렀나 목록 보여주기 위함인데 UI는 아직 없음

**Comment by Pyohwan** [comment]
@silverprize 좋아요 싫어요 누가 눌렀는지 확인하는 UI 가능함?

**Comment by silverprize** [comment]
@Pyohwan 
기존에 이렇게 왔었는데
feeling:"LIKE"
numberOfDislike:1
numberOfLike:1
이렇게 바꾼건가요?
myFeeling:"LIKE"
numberOfDislike:1
numberOfLike:1

**Comment by Pyohwan** [comment]
@silverprize 맞아요

**Comment by Pyohwan** [comment]
@silverprize 그리고 기존에는 단순히 내가 지금 뭐 눌렀는지만 feeling으로 줬는데 이제는 현재 어떤건지를 보여줘요. 좋아요 취소 시키면 null로 감
