### ISSUE TITLE
robots.txt에 sitemap URL 추가

### ISSUE THREAD

**Issue by Pyohwan** [JakduK/jakduk-web#72]
http://webmastertool.naver.com/guide/basic_optimize.naver

보다 보면 robots.txt에 sitemap 추가 하는 방법이 나옵니다.

작두왕 sitemap URL은 아마 https://jakduk.com/sitemap.xml 이 되겠죠.

**Comment by silverprize** [comment]
https://jakduk.com/robots.txt
