### ISSUE TITLE
사진 삭제 API 변경

### ISSUE THREAD

**Issue by Pyohwan** [JakduK/jakduk-web#75]
사진이 댓글에서도 등록 되고, 또한 같은 사진을 여러번 올리면 기존에 업로드 한 사진을 재활용 하면서
글,댓글 <-> 사진 간 다대다 관계가 형성되었습니다.
아무튼, 사진을 지우는 API 요청시 연관된 아이템(글, 댓글) 정보를 넣어 줘야 합니다.
연관된 아이템 정보는 **글, 댓글 편집** 시에만 해당 되며 글쓰기, 댓글 달기시에는 연관된 아이템 정보를 넣지 마세요.

https://staging.jakduk.com:8080/swagger-ui.html#!/Gallery/removeImageUsingDELETE

**Comment by silverprize** [comment]
@Pyohwan from값은 형식이 어떻게 되는지?

**Comment by Pyohwan** [comment]
모델 눌러보면 나와여. BOARD_FREE, BOARB_FREE_COMMENT
