### ISSUE TITLE
SNS 회원 가입 로직 변경 사항

### ISSUE THREAD

**Issue by Pyohwan** [JakduK/jakduk-web#76]
페이스북 로그인이 자꾸 안되어서 살펴보니, 페이스북에서 이메일을 못가져와서 그렇습니다. 또한 과거에 SNS로 가입할 때에는 email을 입력받지 않았었는데 지금은 필수가 되면서 문제가 발생합니다.

### 변경된 API

- SNS 기반 회원 가입시 필요한 회원 프로필 정보 https://staging.jakduk.com:8080/swagger-ui.html#!/Authentication/getSocialAttemptedUserUsingGET

response에 ID가 추가 되었습니다. 필수는 아니므로 null이 될수도 있음.

- SNS 기반 회원 가입 https://staging.jakduk.com:8080/swagger-ui.html#!/User/addSocialUserUsingPOST

위 API 에서 ID가 추가 되었으니, SNS 회원 가입시킬때도 ID를 그대로 넣어주세요.

### UI 상 AJAX로 호출 API 로직이 변경되는 것

새 계정 만들기 페이지인데요.
https://jakduk.com/join/oauth?redir=%2Fhome

별명 중복 체크할때 호출하는 API가 https://staging.jakduk.com:8080/swagger-ui.html#!/User/existUsernameUsingGET 입니다.
근데 조건적으로 바뀌어야 하는데 https://staging.jakduk.com:8080/swagger-ui.html#!/Authentication/getSocialAttemptedUserUsingGET에 얻는 ID가 null이 아니면, https://staging.jakduk.com:8080/swagger-ui.html#!/User/existEmailOnAnonymousUsingGET를 호출해주세요. ID가 null 이면 https://staging.jakduk.com:8080/swagger-ui.html#!/User/existUsernameUsingGET 호출

하.. 점점 복잡해지는군요

**Comment by Pyohwan** [comment]
테스트 할 계정 정보

FACEBOOK
accesstoken EAAKMWimF8eoBAFNJa8iPk8YADlbItfZA24IoWZC54E1tB4YbbtoSyHyqqyGpotLInyhQkACcry4Tf7AxthIfryZBiYFTJ8ZBw3fG7CKElUFn33ybNZAaK6JmeZBbDz2xXHkhEEpGdG6jhGQCaGVmo67plrDqT5gNl7RyAVdCXS4IZCrqHi4V2b8

**Comment by silverprize** [comment]
@Pyohwan 마구잡이로 하지 말고 좀더 생각을 해보심이?

**Comment by silverprize** [comment]
@Pyohwan 이메일없으면 자동생성해도 넣어줘도 되는데

**Comment by Pyohwan** [comment]
@silverprize 이야 어쩜 이리 똑똑한가요?

**Comment by Pyohwan** [comment]
@silverprize 그럼 임시 이메일 발급할테니, 사용자 보고 이메일 다시 입력하라는 메시지를 보여줘야 하는데요.
내 정보 보기 할때 이메일 다시 입력해달라는 메시지 보여주는게 어떤가요?

**Comment by Pyohwan** [comment]
@silverprize 
위에꺼 다 원복하고, 임시 이메일 발급했어요.

### 변경점
GET /api/user/profile/me
내 프로필 정보 보기
https://staging.jakduk.com:8080/swagger-ui.html#!/User/getProfileMeUsingGET

temporaryEmail 값이 true 이면 임시로 발급한 이메일이니깐, 이메일 다시 적어 달라고 문구좀 보여줘요.
