### ISSUE TITLE
로그인 사용자와 글쓴이가 다름!!

### ISSUE THREAD

**Issue by Pyohwan** [JakduK/jakduk-web#79]
![2017-04-28 12 22 21](https://cloud.githubusercontent.com/assets/1825642/25513072/6b324f46-2c0d-11e7-9623-8e7dd5f4758a.png)

왜리럴까요?

**Comment by Pyohwan** [comment]
<img width="1206" alt="2017-04-28 12 27 47" src="https://cloud.githubusercontent.com/assets/1825642/25513172/23896836-2c0e-11e7-9bb6-46f3c74cb196.png">

jwt 토큰은 문제 없는듯

**Comment by silverprize** [comment]
api에서 JSESSIONID를 쿠키로 저장시키고 있는데 확인좀 해주세요.
![2017-04-28 11 37 18](https://cloud.githubusercontent.com/assets/860087/25533503/c638d01e-2c6b-11e7-902b-1ed4dae88bff.png)

**Comment by Pyohwan** [comment]
원래 서버에서 세션을 아예 저장 안했는데, 인증 쪽 말고 사진 업로드 때문에 일부 도입할려고 세션 동작하게 했더니 뒤죽박죽 된듯.

JWT랑 JSESSIONID랑 섞이는거 같네요.

JWT.. 이제 놓아줍시다.
