### ISSUE TITLE
글 상세 안열림

### ISSUE THREAD

**Issue by Pyohwan** [JakduK/jakduk-web#91]
https://api.jakduk.com/api/board/free/834

API는 잘 나오고 있음.

https://jakduk.com/board/free/834

왜 안나오는지 원인을 밝혀주세요.

**Comment by silverprize** [comment]
@Pyohwan 
https://jakduk.com/api/board/free/834/comments

**Comment by Pyohwan** [comment]
@silverprize 에러는 잡을테니. 근데 댓글 못가져온다고 에러 알럿 띄우면 쓰나요. 본문은 나오고 댓글만 안나와야지. 본문 가져오기가 에러면 본문만 안나와야 맞지 않나 싶음.

**Comment by Pyohwan** [comment]
고침 ㅎㅎ
