### ISSUE TITLE
게시판 확장

### ISSUE THREAD

**Issue by Pyohwan** [JakduK/jakduk-web#93]
https://github.com/JakduK/jakduk-api/issues/262
참조

바뀐 내용이 하도 많아서 아래 두개를 서로 비교해가면서 보는게 더 빠를듯..
https://staging.jakduk.com:8080/swagger-ui.html#/Board
https://api.jakduk.com/swagger-ui.html#/BoardFree

**Comment by silverprize** [comment]
아 고통스러워

**Comment by Pyohwan** [comment]
할수있습니다 ㅋㅋ
