### ISSUE TITLE
스웨거 제거 예정 및 MSA 도입 사전 준비를 위한 도메인 변경

### ISSUE THREAD

**Issue by Pyohwan** [JakduK/jakduk-web#94]
### 스웨거 제거 예정
https://github.com/JakduK/jakduk-api/issues/283

앞으로 API 도큐먼트는 다음의 URL을 참고하세요. 아직 API가 몇개 안들어 갔는데 점차적으로 스웨거->acsiidoc로 바꿔가 예정입니다.
https://dev-api.jakduk.com/docs/jakduk-api.html

MSA 도입### 
https://github.com/JakduK/jakduk-api/issues/287
MSA 사전 작업으로 도메인을 변경했습니다.

staging.jakduk.com:8080 -> dev-api.jakduk.com
staging.jakdik.com -> dev-web.jakduk.com

썸네일은 dev.api.jakduk.com/thumbnail/* 사용하면 됩니다.

**Comment by Pyohwan** [comment]
@silverprize 
https://dev-web.jakduk.com/gallery/596cc748807d716ea72bfe61
보면 이미지 경로가 https://dev-image.jakduk.com/gallery/thumbnail/596cc748807d716ea72bfe61
이렇게 되어 있는데, https://dev-api.jakduk.com/gallery/thumbnail/596cc748807d716ea72bfe61 로 해주세요.

아직 이미지 서버는 분리가 안되었어요. 아니면 그냥 도메인만 저리 하나 만들까요?

**Comment by silverprize** [comment]
@Pyohwan production은요?

**Comment by Pyohwan** [comment]
@silverprize 
https://api.jakduk.com 요
